title: My first training page on Github
author: Walfredo Carneiro
email: walfredo.carneiro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning to use Github is the first step to success for any development professional. 
  Collaborative work and the exchange of information between different professionals is
  essential for any project. 
# social links
twitter_username: walfredoscience # DO NOT include the @ character, or else the build will fail!
github_username:  walfredocarneiro # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
